name: Test Workflow

on:
  push: 
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Instalar
        run: pip install pytest
      - name: Probar codigo
        run: python3 test.py
        
 
